// The day counts are reminders to check the soil, never a fixed instruction to water.
export const PLANT_CATALOG = [
  { id:'monstera', name:'Monstera', species:'Monstera deliciosa', group:'Tropicales', light:'indirecte', summer:7, winter:14, tip:'Attends que les premiers centimètres du terreau sèchent. Donne-lui un tuteur si les tiges s’allongent.' },
  { id:'pothos', name:'Pothos', species:'Epipremnum aureum', group:'Tropicales', light:'indirecte', summer:7, winter:14, tip:'Laisse sécher la surface du terreau. Évite le soleil direct de l’après-midi.' },
  { id:'spathiphyllum', name:'Fleur de lune', species:'Spathiphyllum', group:'Tropicales', light:'indirecte', summer:5, winter:10, tip:'Garde le terreau légèrement humide sans laisser d’eau dans la soucoupe.' },
  { id:'ficus', name:'Ficus caoutchouc', species:'Ficus elastica', group:'Tropicales', light:'indirecte', summer:7, winter:14, tip:'Laisse sécher la surface du terreau et tourne le pot de temps en temps.' },
  { id:'sansevieria', name:'Langue de belle-mère', species:'Dracaena trifasciata', group:'Résistantes', light:'indirecte', summer:14, winter:30, tip:'Laisse bien sécher le terreau avant d’arroser, surtout en hiver.' },
  { id:'aloe', name:'Aloe vera', species:'Aloe vera', group:'Succulentes', light:'directe', summer:14, winter:30, tip:'Place-la dans une lumière vive et laisse sécher complètement le terreau entre deux arrosages.' },
  { id:'succulente', name:'Succulente', species:'Succulente', group:'Succulentes', light:'directe', summer:14, winter:30, tip:'Un pot percé et un terreau drainant limitent les racines détrempées.' },
  { id:'cactus', name:'Cactus', species:'Cactaceae', group:'Succulentes', light:'directe', summer:21, winter:45, tip:'En hiver, espace fortement les arrosages et garde une lumière généreuse.' },
  { id:'philodendron', name:'Philodendron grimpant', species:'Philodendron hederaceum', group:'Tropicales', light:'indirecte', summer:7, winter:14, tip:'Laisse sécher la surface du terreau ; une lumière indirecte aide à garder un feuillage dense.' },
  { id:'scindapsus', name:'Scindapsus', species:'Scindapsus pictus', group:'Tropicales', light:'indirecte', summer:7, winter:14, tip:'Une lumière indirecte préserve les marbrures des feuilles. Vérifie la terre avant d’arroser.' },
  { id:'pilea', name:'Pilea', species:'Pilea peperomioides', group:'Résistantes', light:'indirecte', summer:7, winter:14, tip:'Tourne le pot régulièrement pour une croissance équilibrée.' },
  { id:'chlorophytum', name:'Plante araignée', species:'Chlorophytum comosum', group:'Résistantes', light:'indirecte', summer:7, winter:14, tip:'Évite le soleil direct intense et laisse le dessus du terreau sécher légèrement.' },
  { id:'zamioculcas', name:'ZZ plant', species:'Zamioculcas zamiifolia', group:'Résistantes', light:'faible', summer:14, winter:30, tip:'Ses rhizomes stockent l’eau : attends que le pot sèche bien avant d’arroser.' },
  { id:'aglaonema', name:'Aglaonéma', species:'Aglaonema', group:'Résistantes', light:'indirecte', summer:7, winter:14, tip:'Éloigne-le du soleil direct et des courants d’air froid.' },
  { id:'calathea', name:'Calathéa', species:'Goeppertia', group:'Tropicales', light:'indirecte', summer:5, winter:10, tip:'Préfère une humidité ambiante stable ; évite soleil direct et radiateur.' },
  { id:'maranta', name:'Maranta', species:'Maranta leuconeura', group:'Tropicales', light:'indirecte', summer:5, winter:10, tip:'Garde un terreau légèrement humide et une lumière douce.' },
  { id:'alocasia', name:'Alocasia', species:'Alocasia', group:'Tropicales', light:'indirecte', summer:5, winter:12, tip:'Aime une lumière vive sans soleil brûlant ; ralentis l’arrosage quand sa croissance ralentit.' },
  { id:'begonia', name:'Bégonia', species:'Begonia', group:'Fleuries', light:'indirecte', summer:5, winter:10, tip:'Arrose le terreau sans mouiller inutilement le feuillage ; vide la soucoupe.' },
  { id:'anthurium', name:'Anthurium', species:'Anthurium andraeanum', group:'Fleuries', light:'indirecte', summer:6, winter:12, tip:'Une lumière indirecte vive aide la floraison ; garde le terreau drainant.' },
  { id:'orchidee', name:'Orchidée papillon', species:'Phalaenopsis', group:'Fleuries', light:'indirecte', summer:7, winter:12, tip:'Observe les racines et l’écorce ; laisse bien égoutter le pot après l’arrosage.' },
  { id:'fougere', name:'Fougère de Boston', species:'Nephrolepis exaltata', group:'Tropicales', light:'indirecte', summer:4, winter:8, tip:'Évite que la motte sèche complètement ; l’air trop sec brunit les frondes.' },
  { id:'areca', name:'Palmier aréca', species:'Dypsis lutescens', group:'Tropicales', light:'indirecte', summer:6, winter:12, tip:'Donne-lui une lumière vive filtrée et protège-le des radiateurs.' },
  { id:'dracaena', name:'Dragonnier', species:'Dracaena marginata', group:'Résistantes', light:'indirecte', summer:10, winter:20, tip:'Laisse sécher une bonne partie du terreau ; évite l’eau stagnante.' },
  { id:'schefflera', name:'Schefflera', species:'Schefflera arboricola', group:'Résistantes', light:'indirecte', summer:7, winter:14, tip:'Tourne le pot et attends que la surface du terreau sèche avant d’arroser.' },
  { id:'peperomia', name:'Pépéromia', species:'Peperomia obtusifolia', group:'Résistantes', light:'indirecte', summer:10, winter:20, tip:'Ses feuilles charnues supportent une petite sécheresse ; évite d’arroser trop souvent.' },
  { id:'hoya', name:'Hoya', species:'Hoya carnosa', group:'Résistantes', light:'indirecte', summer:10, winter:20, tip:'Attends que le terreau sèche bien ; une lumière indirecte vive favorise la floraison.' },
  { id:'crassula', name:'Arbre de jade', species:'Crassula ovata', group:'Succulentes', light:'directe', summer:14, winter:30, tip:'Offre beaucoup de lumière et laisse sécher complètement la terre.' },
  { id:'echeveria', name:'Échévéria', species:'Echeveria', group:'Succulentes', light:'directe', summer:14, winter:30, tip:'Installe-la près d’une fenêtre lumineuse, avec un pot percé.' },
  { id:'haworthia', name:'Haworthia', species:'Haworthiopsis attenuata', group:'Succulentes', light:'indirecte', summer:14, winter:30, tip:'Elle préfère une lumière vive mais douce ; laisse sécher le terreau entre deux arrosages.' },
  { id:'basilic', name:'Basilic', species:'Ocimum basilicum', group:'Aromatiques', light:'directe', summer:2, winter:5, tip:'Aime la lumière et un terreau régulièrement humide, sans eau stagnante.' },
  { id:'menthe', name:'Menthe', species:'Mentha', group:'Aromatiques', light:'indirecte', summer:3, winter:7, tip:'Vérifie souvent l’humidité de la terre ; pince les tiges pour encourager de nouvelles pousses.' },
  { id:'romarin', name:'Romarin', species:'Salvia rosmarinus', group:'Aromatiques', light:'directe', summer:7, winter:15, tip:'Préfère un emplacement très lumineux et un substrat bien drainé.' },
];
export const CARE_TIPS = [
  'Avant d’arroser, enfonce un doigt dans le terreau : la surface peut sécher alors que les racines sont encore humides.',
  'Après l’arrosage, laisse le pot s’égoutter et vide la soucoupe pour éviter l’eau stagnante.',
  'En hiver, la croissance ralentit souvent : vérifie le terreau et adapte les arrosages plutôt que de suivre le calendrier à la lettre.',
  'Une plante près d’un radiateur peut souffrir de l’air sec. Éloigne les feuilles de la source de chaleur.',
  'Tourne le pot de temps en temps : les feuilles reçoivent ainsi la lumière plus uniformément.',
  'Des feuilles qui jaunissent peuvent avoir plusieurs causes. Vérifie d’abord la lumière, le drainage et l’humidité du terreau.',
  'Quand tu déplaces une plante vers un endroit plus ensoleillé, fais-le progressivement pour éviter de brûler les feuilles.',
];
